### ISSUE TITLE
ImportError: No module named parse

### ISSUE THREAD

**Issue by Hukuta** [linuxmint/folder-color-switcher#18]
> Traceback (most recent call last):
>   File "/usr/share/nemo-python/extensions/nemo-folder-color-switcher.py", line 20, in <module>
>     import os, gettext, locale, urllib.parse, collections
> ImportError: No module named parse

Folder Color 0.0.11
Python 3.6.7

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/folder-color-switcher/pull/16
