### ISSUE TITLE
Custom folder color

### ISSUE THREAD

**Issue by muzena** [linuxmint/folder-color-switcher#2]
Can you add options like in new version nautilus folder color, for choosing custom folder color
http://www.webupd8.org/2014/09/nautilus-nemo-folder-color-extension.html

**Comment by JosephMcc** [comment]
Please see https://github.com/linuxmint/folder-color-switcher/issues/9

Also note if you read the article, doing that has limitations with only working with certain icon themes, breaking the display of emblems, etc.
