### ISSUE TITLE
I cant see option-color-swicher in Linux Mint 20.2

### ISSUE THREAD

**Issue by DiegoBari** [linuxmint/folder-color-switcher#30]
Hello,
I update Linux Mint to 20.2 and now I can't see the option to change the color of any folder in Nemo's contextual menu.
I try to activate and unactivate the plugin, but nothing happen.
It's no a very important issue, but is nice to me to identify folder quicky.
Thanks

System:    Kernel: 5.4.0-77-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 5.0.5 wm: muffin dm: LightDM Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal

**Comment by okaestne** [comment]
If you stop nemo via command line with `nemo -q` and start it again with `nemo`, do you see any messages on the terminal? If so please post them here, thanks.

**Comment by DiegoBari** [comment]
I discovered my mistake. The problem only occurred when traying to switch the color of the folders from "**Favorites**".
From the "real" location of the folder in Nemo, I can switch the color without problems.  😳
Apologies
