### ISSUE TITLE
Mint 21 - bug in Nemo plugins

### ISSUE THREAD

**Issue by DeanneInvernosAntigos** [linuxmint/folder-color-switcher#31]
Today, Nemo plugins simply stopped working. They literally disappeared from Nemo's plugin list, and reinstalling, changing Kernell, resetting Cinnamon, has been useless... They disappeared from the plugin manager: Folder-color-switcher, Nemo compare and Nemo emblems. They just disappeared. Fileroller and Nemo share remained. But ironically, the missing ones appear, they do appear, when I open Nemo as root - and I say ironically, because at least the folder-color-switcher doesn't work, it never worked, like Nemo in root; situation in which the folders have only the default color of the chosen theme. But the case is that all plugins are installed and are recognized with nemo as root, but not as a user.

    The most bizarre however came when I probed the dependencies - reinstalling python-nemo was one of my attempts (it's standard in this kind of case - unsolvable nemo cases are usually the fault of buggy python-nemo reinstallations). As it was useless, I started to probe the dependencies of the dependencies. It is surprise ! A really bizarre bug: Python-nemo says it depends on "libc6 >= 2.4" ( Synaptic said it, I swear I didn't make it up ) Which can only be a hoax, because that version of libc6 doesn't exist ! We're at 2.35-0ubuntu1. So for now, the obvious suspect is an update error (which may even affect other Cinnamom instances, I think). As I recall, my update history for the last 2 days doesn't even include python , nor libc - it was just Kernell (which I tested) libskba8, sudo, git, git-man, zlib1g and zlib1g-dev, and that's all. Other than that, I just changed my root password and installed Buttercup and appimageLauncher.

   Nemo's bugs are rare - both Nemo and Cinnamon tend to run smoothly, but when they have persistent problems, it's desperate (so annoying is it not getting anywhere after trying everything and more). Fortunately, most are fixed with a simple reinstallation, which is not the case. But honestly, the scare was this libc6... After trying everything and searching everywhere, I came here, which is not my place... But my philosophy is that the developer always has to be the first to know, like the kings.

**Comment by Gaturinho** [comment]
So we have:

invernos@Valentine:~$ ls -la /usr/share/nemo-python/extensions/
total 48
drwxr-xr-x 3 root root  4096 out 19 03:37 .
drwxr-xr-x 3 root root  4096 jul 26 12:00 ..
-rw-r--r-- 1 root root  6509 jul 15 11:03 nemo-compare.py
-rw-r--r-- 1 root root  6319 jul 15 11:03 nemo-emblems.py
-rw-r--r-- 1 root root 17675 jul 24 07:11 nemo-folder-color-switcher.py
drwxr-xr-x 2 root root  4096 out  9 12:09 __pycache__
invernos@Valentine:~$ /usr/lib/x86_64-linux-gnu/nemo/nemo-extensions-list
ImportError: could not import gobject (error was: ModuleNotFoundError("No module named 'gi'"))

** (process:27068): WARNING **: 18:44:43.190: pygobject initialization failed

** (process:27068): WARNING **: 18:44:43.190: nemo_python_init_python failed
NEMO_EXTENSION:::NemoFileRoller:::Nemo Fileroller:::Allows managing of archives from the context menu
NEMO_EXTENSION:::MEGAExtension
NEMO_EXTENSION:::NemoShare:::Nemo Share:::Allows you to quickly share a folder from the context menu
invernos@Valentine:~$ dpkg --list | grep nemo
ii  gir1.2-nemo-3.0                                   5.4.3+vanessa                              amd64        libraries for nemo components - gir bindings
ii  libnemo-extension1:amd64                          5.4.3+vanessa                              amd64        libraries for nemo components - runtime version
ii  nemo                                              5.4.3+vanessa                              amd64        file manager and graphical shell for Cinnamon
ii  nemo-compare                                      5.4.1+vanessa                              all          Context menu comparison extension for Nemo file manager
ii  nemo-data                                         5.4.3+vanessa                              all          data files for nemo
ii  nemo-dbg                                          5.4.3+vanessa                              amd64        file manager and graphical shell for Cinnamon - debugging version
ii  nemo-emblems                                      5.4.1+vanessa                              all          Change a folder or file emblem
ii  nemo-fileroller                                   5.4.1+vanessa                              amd64        File Roller integration for Nemo
ii  nemo-megasync                                     4.0.2                                      amd64        Easy automated syncing between your computers and your MEGA cloud drive
ii  nemo-preview                                      5.4.1+vanessa                              amd64        nemo-preview is a quick previewer for nemo
ii  nemo-share                                        5.4.1+vanessa                              amd64        Nemo extension to share folder using Samba
ii  python-nemo                                       5.4.1+vanessa                              amd64        Python binding for Nemo components

Hope it is enough, and lead to a developer solution to **prevent** the bug and improve stability for all users. Not just to fix it.

**Comment by mtwebster** [comment]
Try:
```
apt install --reinstall python3-gi
```
and
```
python3 -c "import gi;print(gi)"
```
and try to run `nemo-extensions-list` again

**Comment by Gaturinho** [comment]
Looks like it won't be that easy. Following his instructions, the reinstall went fine, the rest was scrapped:

invernos@Valentine:~$ apt install --reinstall python3-gi
[sudo] senha para invernos:          
Sinto muito, tente novamente.
[sudo] senha para invernos:           
Lendo listas de pacotes... Pronto
Construindo árvore de dependências... Pronto
Lendo informação de estado... Pronto        
0 pacotes atualizados, 0 pacotes novos instalados, 1 reinstalados, 0 a serem removidos e 0 não atualizados.
É preciso baixar 229 kB de arquivos.
Depois desta operação, 0 B adicionais de espaço em disco serão usados.
Obter:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3-gi amd64 3.42.1-0ubuntu1 [229 kB]
Baixados 229 kB em 4s (56,5 kB/s)    
(Lendo banco de dados ... 708128 ficheiros e directórios actualmente instalados.)
A preparar para desempacotar .../python3-gi_3.42.1-0ubuntu1_amd64.deb ...
A descompactar python3-gi (3.42.1-0ubuntu1) sobre (3.42.1-0ubuntu1) ...
Configurando python3-gi (3.42.1-0ubuntu1) ...
invernos@Valentine:~$ python3 -c "import gi;print(gi)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'gi'
invernos@Valentine:~$ nemo-extensions-list
nemo-extensions-list: comando não encontrado

    Nem com "sudo" reconheceu o último comando. 

invernos@Valentine:~$ sudo nemo-extensions-list
sudo: nemo-extensions-list: comando não encontrado

    But as for the system having scrapped "nemo-extensions-list"; I tried again the command from your previous communication, and:

invernos@Valentine:~$ /usr/lib/x86_64-linux-gnu/nemo/nemo-extensions-list
ImportError: could not import gobject (error was: ModuleNotFoundError("No module named 'gi'"))

** (process:55431): WARNING **: 00:48:49.530: pygobject initialization failed

** (process:55431): WARNING **: 00:48:49.530: nemo_python_init_python failed
NEMO_EXTENSION:::NemoFileRoller:::Nemo Fileroller:::Allows managing of archives from the context menu
NEMO_EXTENSION:::MEGAExtension
NEMO_EXTENSION:::NemoShare:::Nemo Share:::Allows you to quickly share a folder from the context menu

    PS: I hope you don't mind that Github is identifying me randomly, sometimes as one person (Deanne Winters Old), sometimes with another (Gaturinho). It always happens, but I'm still the same...

**Comment by Gaturinho** [comment]
...Oops, I noticed a stupid mistake of mine: I followed your instructions ( "apt install --reinstall python3-gi" ) but forgot to include sudo :

sudo apt install --reinstall python3-gi

    I should have noticed! Paying attention is the least I owe you!

    However, the result remains unchanged:

winters@Valentine:~$ sudo apt install --reinstall python3-gi
Reading package lists... Done
Building dependency tree... Done
Reading status information... Ready
0 packages updated, 0 new packages installed, 1 reinstalled, 0 to be removed and 0 not updated.
You need to download 229 kB of files.
After this operation, an additional 0 B of disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3-gi amd64 3.42.1-0ubuntu1 [229 kB]
Downloaded 229 kB in 2s (139 kB/s)
(Reading database... 708128 files and directories currently installed.
)
Preparing to unpack .../python3-gi_3.42.1-0ubuntu1_amd64.deb ...
Unpacking python3-gi (3.42.1-0ubuntu1) over (3.42.1-0ubuntu1) ...
Configuring python3-gi (3.42.1-0ubuntu1) ...
winters@Valentine:~$ sudo apt install -f
Reading package lists... Done
Building dependency tree... Done
Reading status information... Ready
0 packages updated, 0 new packages installed, 0 to be removed and 0 not updated.
winters@Valentine:~$ python3 -c "import gi;print(gi)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'gi'
winters@Valentine:~$ nemo-extensions-list
nemo-extensions-list: command not found

**Comment by Gaturinho** [comment]
Additionally, nothing unusual in the session logs. It only registers I open the terminal > does not register and reinstallation of python3-gui.

Oct 20 01:07:19 Valentine systemd[3724]: gnome-terminal-server.service: Consumed 5.627s CPU time.
Oct 20 01:07:33 Valentine dbus-daemon[3746]: [session uid=1000 pid=3746] Activating via systemd: service name='org.gnome.Terminal' unit='gnome-terminal-server.service' requested by ':1.118' (uid=1000 pid=126977 comm="/usr/bin/gnome-terminal.real -- sh -c tail -f /var" label="unconfined")
Oct 20 01:07:33 Valentine systemd[3724]: Starting GNOME Terminal Server...
Oct 20 01:07:33 Valentine dbus-daemon[3746]: [session uid=1000 pid=3746] Successfully activated service 'org.gnome.Terminal'
Oct 20 01:07:33 Valentine systemd[3724]: Started GNOME Terminal Server.
Oct 20 01:07:33 Valentine systemd[3724]: Started VTE child process 127004 launched by gnome-terminal-server process 126980.
Oct 20 01:11:06 Valentine dbus-daemon[3746]: [session uid=1000 pid=3746] Activating via systemd: service name='org.gnome.Terminal' unit='gnome-terminal-server.service' requested by ':1.120' (uid=1000 pid=141109 comm="/usr/bin/gnome-terminal.real -- sh -c tail -f /var" label="unconfined")
Oct 20 01:11:06 Valentine systemd[3724]: Starting GNOME Terminal Server...
Oct 20 01:11:06 Valentine dbus-daemon[3746]: [session uid=1000 pid=3746] Successfully activated service 'org.gnome.Terminal'
Oct 20 01:11:06 Valentine systemd[3724]: Started GNOME Terminal Server.
Oct 20 01:11:07 Valentine systemd[3724]: Started VTE child process 141136 launched by gnome-terminal-server process 141112.

**Comment by mtwebster** [comment]
Have you done anything like messing with your system installation of python, or installing packages using pip (python package installer)?

Please show the output to:
```
python3 -c "import sys;print(sys.path)"
```

**Comment by Gaturinho** [comment]
Yes, I have python packages installed via pip; incidentally, this is not a clean install, and I must have several legacy git/homebrew packages from the previous install. I don't uninstall them just because I don't know how to do a safe uninstall of git packages, either via homebrew or pip, after all, homebrew is not dpkg or apt, which consider the whole chain of dependencies before installing/uninstalling something. That's what it takes to be a layman...

    The terminal output for the command is:

python3 -c "import sys;print(sys.path)"
['', '/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python310.zip', '/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib /python3.10', '/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/lib-dynload', '/home/winters/.local/lib/python3.10 /site-packages', '/home/linuxbrew/.linuxbrew/Cellar/python@3.10/3.10.8/lib/python3.10/site-packages', '/home/linuxbrew/.linuxbrew/Cellar/pygments/2.13 .0/libexec/lib/python3.10/site-packages']

    I would be immensely happy if you could tell me, what exactly I have to uninstall, and how safely.

**Comment by mtwebster** [comment]
Hmmm....

One last command:
```
which python3
```
if that says *anything* other than `/usr/bin/python3` (such as ... .local/bin/python3 or similar), go to that file and rename it to something else (don't delete it just yet). Do the same for any files there starting with `pip`.

That *may* be enough to unbreak things. If it does, you can go delete those renamed files, and you should be able to entirely remove `/home/linuxbrew/.linuxbrew` as well as `/home/winters/.local/lib/python3.10`.

**Comment by okaestne** [comment]
> if that says _anything_ other than `/usr/bin/python3` (such as ... .local/bin/python3 or similar), go to that file and rename it to something else (don't delete it just yet). Do the same for any files there starting with `pip`.

In this case, there's likely a script in ~/.bashrc that sets this up.

**Comment by Gaturinho** [comment]
First of all: Everything is normal again, apart from a recent bug ( the one I mentioned ) in the download dialogs which I will report in another post in a few minutes. Everything went well, **_with no sequelae_**. It was a victory of stability over bugs!

    But while uninstalling Homebrew is a great suggestion, I can't do without it. It might not be the safest thing in the world -- just not having "sudo" is risky enough -- but I can't do without it. Here I have a lot of software installed via brew. And the most important thing is accessibility: I retired from the audit firm 10 years ago due to congenital neurological problems that got worse: I have no concentration anymore, and I suffer from a very serious attention deficit, to the point that I even have difficulties finding the pointer of the mouse, even leaving it in a huge size. That's why I installed a special cursor, Bibata-Bee ( https://www.gnome-look.org/p/1572498 ), which is an animated cursor that draws a lot of attention, and I even thought about suggesting it to be included in Mint's accessibility options. It makes a huge difference in my productivity ( because I don't have to keep looking for the pointer on the screen ) and it reduces my effort. But it does require clickgen, which is only available via git, but it's so hard to install that need calling homebrew itself; with pip. And look, I'm terrified of the pip. It looks like a bomb, has no safeguards.

It took me a few hours working on Homebrew, to eliminate all the error warnings and risks of damage. I had to run "brew doctor" for the diagnosis, rename some more files as ".old", run "brew cleanup", "brew config" and "brew update". There are still a lot of warnings ( of strange files -- the ones I've renamed ), but I'll have about 6 months to check if I've damaged any other software installed via brew, and then I'll be able to delete ( or at least move ) the renamed files.

    I want to thank you again for the help, since I was on my last option. I looked for reports of similar problems on the Mint forums with no success, so I assumed it was either a new bug and I happened to be its first victim, or I had screwed up my environment variables. So I would need expert help, who knew where to start looking, and knew the precise diagnostic tools. ( About screwing up my environment variables, I always thought there should be some tool to back them up, independent of Timeshift, because that's one of the problems it doesn't solve, and it doesn't help !  )

    In time: Python installed via pip was 3.10, but I installed it on mint 20.1, and it was legacy to here because this is not a clean install. This system here is all customized (even the mint icon in grub was customized by hand), so configuring it from scratch every time I reinstall is not very feasible. But from what I've seen in Homebrew, it wasn't the installed python that caused the problem, it would have just been ignored since the current one is Python 3.10.6. The real problem was a .pydistutils.cfg file in the home folder, which interfered with it... I hope this information is somehow useful for stability development.

   And taking the opportunity to say, this mint 21 is more stable than 20.3, even with less problems with "geteca" ( GTK 4 ), although the problem of loss of focus persists, but it's not that bad anymore... Well, I'll go to the next bug, in a separate post! HAPPINESS FOR YOU !

**Comment by clefebvre** [comment]
Closing this.

Just a quick note for people who develop in python and require to install local deps/versions, you can use virtual environments, it simplifies things a lot.
