### ISSUE TITLE
Unexpected Behavior from Nemo on non Cinnamon DEs

### ISSUE THREAD

**Issue by JanHendrikGarvens** [linuxmint/folder-color-switcher#36]
https://github.com/linuxmint/folder-color-switcher/blob/c9d1a2b9c7f40ff7bb77ee74a277988bb8a4adf2/usr/share/nemo-python/extensions/nemo-folder-color-switcher.py#L322
I am using Nemo on XFCE with the Mint-Y-Aqua icon-theme (Arch/Nixos) and had problems getting folder-color-switcher to work.
After a lot of digging, I found out that Nemo follows the currently set gtk icon theme while nemo-folder-color-switcher.py follows the gtk icon theme **set in cinnamon**, resulting in unexpected behavior if current icon theme =/= cinnamon icon theme (on a lot of distros the default cinnamon icon theme is Adwaita)

I had nemo-folder-color-switcher.py follow the current gtk icon theme by changing the line on my machine to:
```python
        icon_theme_name = Gtk.Settings.get_default().get_property("gtk-icon-theme-name")
```
Is this worth considering? I couldn't find if using folder-color-switcher on non Cinnamon/Linux Mint is supported or not...

**Comment by mtwebster** [comment]
Yeah using GtkSettings would be more reliable in other environments (and in Cinnamon, it's set based off of the `icon-theme` key anyhow).

I'm not really sure how well this will work in other themes - we've mainly designed it around Mint-provided ones.
