### ISSUE TITLE
Can't change folder colour while using Mint-Y icon theme

### ISSUE THREAD

**Issue by KiszonkaMariana** [linuxmint/folder-color-switcher#7]
I can't see nemo folder color switcher while using Mint-Y icon theme, but as a root, there is only locked switcher.  I can change folder color only while using Mint-X icon theme.

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/folder-color-switcher/commit/3c72668c6ce3231c2234174298309ddb3d0c42a4
