### ISSUE TITLE
Picking own colors

### ISSUE THREAD

**Issue by KiszonkaMariana** [linuxmint/folder-color-switcher#9]
There are not much colors you can choose in folder-color-switcher and you can only use it with mint-x theme, so what about adding option for picking own colors or just adding basic colors like these from rainbow, white, gray and black? There is no need for creating separated icon themes for mint-y, like mint-x-yellow, aqua etc. (with mint-x theme), if there was just one version, that would be colored.

**Comment by JosephMcc** [comment]
The design of the color chooser depends on the theme providing the various colors so this isn't really feasible.
